# Importación de la edición de python
from python:3.12-slim

# Creación de carpeta de trabajo del contenedor
workdir /app

# Se copian los requerimientos del servidor (El " . " copia y pega a la carpeta de trabajo igualmente el archivo)
copy requirements.txt .

# Se instalan los requerimientos
run pip install --no-cache-dir -r requirements.txt

# Copiar el código del API
copy ./app ./app

# Se expone
expose 5000

# Comando de ejecución FastAPI (uvicorn para levantar el servidor, 
# [carpeta del proyecto.nombre del proyecto:instancia de la variable con FastAPI] para indicar la ruta,
# --host para el localhost,
# 0.0.0.0 para indicar el puerto,
# 5000 puerto,
# para actualizar el proyecto constantemente)
cmd ["uvicorn","app.main:app", "--host", "0.0.0.0", "--port", "5000", "--reload"]
